DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('pool/', views.pool, name='pool'),
    path('blog/', views.blog, name='blog'),
    path('newpost/', views.newpost, name='newpost'),
    path('(<parametr>)/', views.blogpost, name='blogpost'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Вход в учётную запись',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('registration/', views.registration, name='registration'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/models.py
"""
Definition of models.
"""

from tkinter import Label
from django.db import models
from datetime import datetime
from django.contrib import admin
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length = 100, unique_for_date = "posted", verbose_name = "Заголовок")
    discription = models.TextField(verbose_name = "Краткое содержание")
    content = models.TextField(verbose_name = "Полное содержание")
    posted = models.DateTimeField(default = datetime.now(), db_index = True, verbose_name = "Опубликована")
    image = models.FileField(default='temp.png',upload_to = 'postImage/', verbose_name = "Изображение")
    video = models.FileField(default='temp.mp4',upload_to = 'postVideo/', verbose_name = "Видео")
    videoposter = models.FileField(default='temp.png',upload_to = 'postVideo/', verbose_name = "Постер видео")
    
    
    def get_absolute_url(self):
        return reverse("blogpost", args=[str(self.id)])   

    def __str__(self):
        return self.title
    
    class Meta:
        db_table = "Posts"
        ordering = ["-posted"]
        verbose_name = "статья блога"
        verbose_name_plural = "статьи блога"
        
class Comment(models.Model):
    text = models.TextField(verbose_name = "Комментарий")
    date = models.DateTimeField(default=datetime.now(), db_index=True, verbose_name= "Дата")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name="Статья")

    def __str__(self):
        return 'Комментарий %s к %s : %s'%(self.author,self.post,self.text)

    class Meta:
        db_table = "Comments"
        ordering = ["-date"]
        verbose_name = "комментарии"
        verbose_name_plural = "коментарии к статьям блога"
     
admin.site.register(Blog)
admin.site.register(Comment)

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<hr>
<img src='../../static/app/content/Logo.png' width="200" height="200" />
<h3>{{ message }}</h3>

<div class="row">
    <div class="col-md-8">
        <label>
            Создатель инди-игр Стив Габри из Питтсбурга, отмеченный наградами, занимается созданием популярных игр уже 11 лет. Как основатель Portable Moose (2015),
            Стив наиболее известен своим сольным созданием мрачной приключенческой игры Sally Face (2016-2019). Он носит множество шляп, в том числе художника, музыканта,
            писателя и геймдизайнера, и часто черпает вдохновение в своих мечтах.
        </label>
        <label>
            Карьера Стива также включает в себя соучредительство Wither Studios (2010, разработчик игр) и работу с ними в качестве креативного директора Crowman & Wolfboy (2013,
            мобильный платформер), художника / дизайнера в Immure (2019, психологический хоррор) и художника / дизайнера в Touched by an Outer God (2020, экшн кадры ужасов).
        </label>
    </div>
</div>
{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<hr>

{% if user.is_superuser %}
    <p style="text-align: right"><a class="btn btn-primary btn-large" href="{% url 'newpost' %}">+ Добавить статью</a></p>
{% endif %}

{% for post in posts %}
    <div class="jumbotron">
        <h2>{{ post.title }}</h2>
        <p>{{ post.discription }}</p>
        <h5>{{ post.posted }}</h5>
        <p><a class="btn btn-default" href="{% url 'blogpost' parametr=post.id %}">Читать далее &raquo; </a></p>
    </div>
{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}


<h2>{{ post_l.title }}</h2>
<hr>

<div class="row">
    <div class="col-md-12">
        {% if post_l.image and post_l.image.url != '/media/temp.png' %}
        <img class="displayed" src="{{post_l.image.url}}" alt="Картинка" width="960" height="540" style="display: block; margin-left: auto; margin-right: auto" />
        {% endif %}

        {% if post_l.video and post_l.video.url != '/media/temp.mp4' %}
        <div>
            <video class="displayed" src={{post_l.video.url}} controls="controls" alt="Видео" width="960" height="540" style="display: block; margin-left: auto; margin-right: auto" poster="{{post_l.videoposter.url}}" />
        </div>
        {% endif %}

        <h3>{{ post_l.content }}</h3>
        <hr>
        {% if user.is_authenticated %}
        <h5>Добавить комментарий</h5>
        <form method="POST">
            {% csrf_token %}
            <div>
                <p>
                    <label for="id_text">Коментарий:</label>
                    <textarea class="form-control" name="text" cols="100" rows="1" required id="id_text"></textarea>
                </p>
                <button type="submit" class="save btn btn-primary btn-large"> Отправить комментарий </button>
            </div>
        </form>
        {% else %}
        <h5> Для добавления своего комментария, пожалуйста, авторизуйтесь </h5>
        {% endif %}
        {% for comment in comments %}
        <div>
            <hr>
            <h5 style="color: rgb(248,177,120) "> {{comment.author}} </h5>
            <p> {{comment.text|linebreaksbr}} </p>
            <h8 style="color:rgb(128,128,128)"> {{comment.date}} </h8>
        </div>
        {% endfor %}
        <br>
        <p><a class="btn btn-default" href="{% url 'blog' %}">&laquo; Назад</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<hr>
<h3>{{ message }}</h3>

<address>
    <strong>Twiter:</strong>   <a href="https://twitter.com/PortableMoose">twitter.com</a><br />
    <strong>YouTube:</strong>   <a href="https://www.youtube.com/portablemoose">www.youtube.com</a><br />
    <strong>Instagram:</strong> <a href="https://www.instagram.com/portablemoose/">www.instagram.com</a><br />
    <strong>Discord:</strong> <a href="https://discord.com/invite/dzdBCCX">discord.com</a>
</address>

<address>
    <strong>Официальный сайт:</strong>   <a href="https://www.portablemoose.com">portablemoose.com</a><br />
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% load static %}

{% block content %}

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <img src="{% static 'app/content/aboutSF.png' %}" width="228" height="324" />
        </div>
        <div class="col-md-8">
            <h1>Sally Face</h1>
            <h2>История</h2>
            <p class="lead">
                Sally Face - мрачная приключенческая игра о мальчике с протезированным лицом. Сэл использует свою портативную игровую систему,
                чтобы разговаривать с мертвыми и узнавать их истории. После череды загадочных убийств Сэл и трое его друзей обнаруживают нечто
                поистине зловещее, бросающее тень на их маленький городок.
            </p>
            <h2>Эпизоды</h2>
            <p class="lead">
                Всего "Салли Фейс" состоит из пяти серий. Первая серия содержит краткое введение, которое значительно расширяется в последующих сериях.
            </p>
        </div>
        <div class="col-md-1"><p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Узнать больше &raquo;</a></p></div>
    </div>
</div>
<h1>Награды</h1>
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
        <li data-target="#myCarousel" data-slide-to="6"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'app/content/banners/Baner1.png'%} " alt="Первый слайд" class="img-responsive" />
            <br><br><br>
            <div class="carousel-caption" role="option">
            </div>
        </div>
        <div class="item">
            <img src="{% static 'app/content/banners/Baner2.png'%}" alt="Второй слайд" class="img-responsive" />
            <br><br><br>
            <div class="carousel-caption" role="option">
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/banners/Baner3.png'%} " alt="Третий слайд" class="img-responsive" />
            <br><br><br>
            <div class="carousel-caption" role="option">
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/banners/Baner4.png'%} " alt="Третий слайд" class="img-responsive" />
            <br><br><br>
            <div class="carousel-caption" role="option">
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/banners/Baner5.png'%} " alt="Третий слайд" class="img-responsive" />
            <br><br><br>
            <div class="carousel-caption" role="option">
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/banners/Baner6.png'%} " alt="Третий слайд" class="img-responsive" />
            <br><br><br>
            <div class="carousel-caption" role="option">
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/banners/Baner7.png'%} " alt="Третий слайд" class="img-responsive" />
            <br><br><br>
            <div class="carousel-caption" role="option">
            </div>
        </div>
    </div>
</div>

<h1>Итересные материалы</h1>
<div id="myCarousel2" class="carousel slide" data-ride="carousel" data-interval="2000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel2" data-slide-to="1"></li>
        <li data-target="#myCarousel2" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <a href="https://shop.portablemoose.com/">
                <img src="{% static 'app/content/banners2/banner1.png'%} " alt="Первый слайд" class="img-responsive" />
            </a>
            <dir style="background-color: rgba(0,0,0,0.5); position: absolute; right: 0; bottom: -15px; left: 0;  padding-bottom: 10%; color: #fff;">
                <div class="carousel-caption" role="option">
                    <p>В этом году также появились отличные новые товары Sally Face. У нас распродажа!</p>
                </div>
            </dir>
        </div>
        <div class="item">
            <a href="http://www.strangenightmares.com/">
                <img src="{% static 'app/content/banners2/banner2.png'%}" alt="Второй слайд" class="img-responsive" />
            </a>
            <dir style="background-color: rgba(0,0,0,0.5); position: absolute; right: 0; bottom: -15px; left: 0; padding-bottom: 10%; color: #fff;">
                <div class="carousel-caption" role="option" >
                    <p>Это эксклюзивное издание Sally Face: Strange Nightmares для Kickstarter / предварительного заказа. Оно включает в себя все, что есть в розничной продаже игры, только лучше!</p>
                </div>
            </dir>   
        </div>
        <div class="item">
            <a href="http://store.steampowered.com/app/541570/">
                <img src=" {% static 'app/content/banners2/banner3.png'%} " alt="Третий слайд" class="img-responsive" />
            </a>
            <dir style="background-color: rgba(0,0,0,0.5); position: absolute; right: 0; bottom: -15px; left: 0; padding-bottom: 10%; color: #fff;">
                <div class="carousel-caption" role="option">
                    <p>Погрузитесь в мрачное приключение мальчика с протезом на лице и тяжелым прошлым. Распутайте зловещую тайну истории Салли, чтобы отыскать правду, скрытую завесой тьмы.</p>
                </div>
            </dir>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel2" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel2" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Начало работы</h2>
        <p>
            Django предоставляет вам мощный, основанный на шаблонах способ создания динамических веб-сайтов, который
            позволяет четко разделить задачи и дает вам полный контроль над разметкой
            для приятной и гибкой разработки.
        </p>
        <p><a class="btn btn-default" href="https://djangobook.com/django-tutorials/">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Получите больше библиотек</h2>
        <p>Индекс пакетов Python - это хранилище программного обеспечения для языка программирования Python.</p>
        <p><a class="btn btn-default" href="https://pypi.org/">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>Вы можете легко опубликовать в Microsoft Azure с помощью Visual Studio. Узнайте, как вы можете разместить свое приложение, воспользовавшись бесплатной пробной версией уже сегодня.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Узнать больше &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Мое приложение Django</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/Logo.png' %}" alt="logo" width="30" height="30"/> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'pool' %}">Обратная связь</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Мое приложение Django</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте локальную учетную запись для входа в систему.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя:</label><br>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль:</label><br>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильное имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">{{ user.username }}</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Войти</a></li>
    <li><a href="{% url 'registration' %}">Регистрация</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% include 'app/blog.html' %}

{% block content %}

<h2>{{ title }}</h2>
<hr>
<div class="row">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-8">
            <div class="form-group">
                <label for="id_title" class="control-label">Заголовок:</label>
                <input class="form-control" type="text" name="title" maxlength="100" required id="id_title" />
            </div>
            <div class="form-group">
                <label for="id_discription" class="control-label">Краткое содержание:</label>
                <textarea class="form-control" name="discription" cols="40" rows="10" required="" id="id_discription"></textarea>
            </div>
            <div class="form-group">
                <label for="id_content" class="control-label">Полное содержание:</label>
                <textarea class="form-control" name="content" cols="40" rows="10" required="" id="id_content"></textarea>
            </div>
            <div class="form-group">
                <label for="id_image" class="control-label">Картинка:</label>
                <input class="form-control" type="file" name="image" id="id_image">
            </div>
            <div class="form-group">
                <label for="id_video" class="control-label">Видео:</label>
                <input class="form-control" type="file" name="video" id="id_video">
            </div>
            <div class="form-group">
                <label for="id_videoposter" class="control-label">Постер видео:</label>
                <input class="form-control" type="file" name="videoposter" id="id_videoposter">
            </div>
            <p>
                <a class="btn btn btn-default" href="{% url 'blog' %}">&laquo; Назад</a>
                <button type="submit" class="save btn btn-default">Опубликовать</button>
            </p>
        </div>
    </form>
</div>
{% endblock %}

app/templates/app/pool.html
{% extends "app/layout.html" %}
{% block content %}

{% if user.is_authenticated %}

    {% if form != None %}

<h2>Форма обратной связи</h2>
<hr>
<div class="row">
    <div class="col-md-8">
        <form method="post">
            {% csrf_token %}
            <label fpr="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
            {{ form.name }}<br>
            <label fpr="{{ form.gender.id_for_label }}">{{ form.gender.label }}:</label>
            {{ form.gender }}<br>
            <label fpr="{{ form.country.id_for_label }}">{{ form.country.label }}:</label>
            {{ form.country }}<br>
            <label fpr="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
            {{ form.email }}<br>
            <label fpr="{{ form.message.id_for_label }}">{{ form.message.label }}:</label>
            {{ form.message }}<br>
            {{ form.agreement }} <label fpr="{{ form.agreement.id_for_label }}">{{ form.agreement.label }}</label>
            <br>
            <input class="btn btn-default" type="submit" value="Отправить" />
        </form>
    </div>
</div>
    {% else %}
<h2>Благодарим за предоставленный отзыв</h2>
<hr>
<h3>Вы сообщили следующее:</h3>
<br>
<div class="row">
    <div class="col-md-8">
        <span>Имя:</span> {{ data.name }}<br>
        <span>Пол:</span> {{ data.gender }}<br>
        <span>Страна:</span> {{ data.country }}<br>
        <span>E-mail:</span> {{ data.email }}<br>
        <span>Соглашение:</span> {{ data.agreement }}<br>
        <span>Сообщение:</span> {{ data.message }}
    </div>
</div>
    {% endif %}
{% else %}
<h2>Форма обратной связи</h2>
<div class="row">
    <div class="col-md-8">
        <form method="post">
            <br><br><br>
            <span>Пожалуйста авторизуйтесь или зарегистрируйтесь для продолжения.</span>
            <br><br><br>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Регистрация пользователя</h2>
<hr>
<div class="row">
    <div class="col-md-8">
        <form method="POST">
            {% csrf_token %}
            <div>
                <p>
                    <label for="id_username">Имя пользователя: </label>
                    <input class="form-control" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username" />
                    <span class="helptext"></span>
                </p>
                <ul>
                    <li> "Не более 150 символов."</li>
                    <li> "Только буквы, цифры и символы @/./+/-/_."</li>
                </ul>
                <br>
                <p>
                    <label for="id_password1">Пароль: </label>
                    <input class="form-control" type="password" name="password1" autocomplete="new-password" required id="id_password1" />
                    <span class="helptext"></span>
                </p>
                <p>
                    <label for="id_password2">Подтверждение пароля:</label>
                    <input class="form-control" type="password" name="password2" autocomplete="new-password" required id="id_password2" />
                    <span class="helptext"></span>
                </p>
                <ul>
                    <li> "Пароль не должен быть слишком похож на другую вашу личную информацию."</li>
                    <li> "Ваш пароль должен содержать как минимум 8 символов."</li>
                    <li> "Пароль не должен быть слишком простым и распространенным."</li>
                    <li> "Пароль не может состоять только из цифр."</li>
                </ul>
                <br>
                <button type="submit" class="save btn btn-default"> Зарегистрировать </button>
            </div>
        </form>
    </div>
</div>

    {% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Видео</h2>
<hr>

<div class="jumbotron">
    <h2>Видео 1</h2>
    <video src="/media/app/static/app/content/postVideo/video1.mp4" controls="controls" width="960" height="540" poster="/media/app/static/app/content/postVideo/poster1.png" />

    <!--<h2>Видео 2</h2>
    <video src="/media/app/static/app/content/postVideo/video2.mp4" controls="controls" width="" height="" poster="/media/app/static/app/content/postVideo/poster2" />-->
</div>

{% endblock %}